projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - app/_lib/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - app/_lib/graphql/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/_lib/graphql/API.ts
        docsFilePath: app/_lib/graphql
        region: ap-northeast-1
        apiId: gqpyt2ufknfnxhwvd7cijql2u4
        frontend: javascript
        framework: react
        maxDepth: 2
