// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ConfirmSignUpInput struct {
	Username         string `json:"username"`
	Email            string `json:"email"`
	ConfirmationCode string `json:"confirmationCode"`
}

type Mutation struct {
}

type Query struct {
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInResponse struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Tokens  *Tokens `json:"tokens,omitempty"`
}

type SignUpInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Tokens struct {
	AccessToken  string `json:"accessToken"`
	IDToken      string `json:"idToken"`
	RefreshToken string `json:"refreshToken"`
}

type User struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
