// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ConfirmSignUpInput struct {
	Username         string `json:"username"`
	Email            string `json:"email"`
	ConfirmationCode string `json:"confirmationCode"`
}

type Mutation struct {
}

type Query struct {
}

type SignUpInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
